### PR TITLE
Lh363 merge search menu

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by jayallen** [comment]
This is on hold until we get the go-ahead from Dan.

**Comment by MikeThomsen** [comment]
Dan messaged me and gave me the go ahead on this.

**Comment by jayallen** [comment]
Same question here.  Did you delete the lh363-merge-search-menu and if so was the above the only commit?

**Comment by MikeThomsen** [comment]
Yes

**Comment by jayallen** [comment]
I went ahead and committed this since it's so small and all the branches and pull requests clutter my view.  You'll see this in the next push.

**Pull request closed without merging**
