### PR TITLE
Lh 531 extlib reset

### PR DESCRIPTION
**Pull request by tima**
I ran the test suite on this. I'm not sure how many of these errors and warnings this work created. I suspect a couple that I'll need to look in to. In the meanwhile let's get this in the repo and out for further testing.

### CODE REVIEW

**Comment by jayallen** [comment]
Hey Tim, I'm not comfortable with this checkin.  I only looked at the first seven modules it removes and found the following:
- File::Temp
  - Used all OVER the application
  - Used by Log4MT and the eventual Melody logging framework
  - Used by XML::SAX::PurePerl::Reader::URI which is used by XML::SAX which is used by the backup and restore system and MT::Util
- I18N::LangTags
  - Used by Locale/Maketext and hence MT::L10N both directly and through I18N::LangTags::Detect

In just browsing the list, I saw these:
- XML::Atom - Used by lib/MT/AtomServer.pm
- XML::XPath - Used by lib/MT/AtomServer.pm + OpenID auth

Can you check your methodology for compiling dependencies because something is wrong if it's not picking these up.

**Comment by tima** [comment]
@@@
timair-3:melody tima$ corelist File::Temp

File::Temp was first released with perl 5.006001
timair-3:melody tima$ corelist I18N::LangTags

I18N::LangTags was first released with perl 5.007003
@@@

XML::Atom and XML::Path where removed because they rely on one or more compiled modules. 

For instance, Including XML::Atom in extlib causes check.cgi to report all systems go even if you don't have XML::LibXML or XML::Parser/XML::XPath installed. You only learn that once you try and use something with XML::Atom. (The dynamic loading trickery make those missing dependencies a run-time error rather than a compiled time error that check.cgi is banking on in its tests.

**Comment by jayallen** [comment]
Ah, well that makes a lot of difference.  Sorry about closing this ticket; I didn't intend to assuming it was me who did it.

**Comment by jayallen** [comment]
Hey I've got a huge conflict. Can you tell me what the correct Makefile looks like?

```
<<<<<<< HEAD
        # From Bundle::Melody::extlib (please keep in sync)
        'Archive::Extract'            => 0.08,
        'Attribute::Params::Validate' => 1.07,
        'bignum'                      => 0.23,
        'Cache'                       => 0,
        'CGI'                         => 3.50,
        'Class::Accessor'             => 0.22,
        'Class::Data::Inheritable'    => 0.06,
        'Class::ErrorHandler'         => 0.01,
        'Class::Trigger'              => 0.1001,
        'Crypt::DH'                   => 0.06,
        'Data::ObjectDriver'          => 0.06,
        'File::Copy::Recursive'       => 0.23,
        'File::Temp'                  => 0.12,
        'Heap::Fibonacci'             => 0.71,
        'HTML::Template'              => 2.8,
        'I18N::LangTags'              => 0.35,
        'Image::Size'                 => 2.93,
        'IO::Scalar'                  => 2.110,
        'IPC::Cmd'                    => 0.24,
        'Jcode'                       => 0.88,
        'JSON'                        => 2.12,
        'Locale::Maketext'            => 1.13,
        'Log::Log4perl'               => 0,
        'Log::Dispatch'               => 0,
        'Lucene::QueryParser'         => 1.04,
        'LWP'                         => 5.829,
        'Math::BigInt'                => 1.63,
        'MIME::Charset'               => 0.044,
        'MIME::EncWords'              => 0.040,
        'Module::Load'                => 0.10,
        'Module::Load::Conditional'   => 0.08,
        'Net::OAuth'                  => 0.11,
        'Net::OpenID::Consumer'       => 1.03,
        'Params::Check'               => 0.24,
        'Params::Validate'            => 0.73,
        'Sub::Install'                => 0,
        'SOAP::Lite'                  => '0.710.08',
        'TheSchwartz'                 => 1.07, # CPAN no like
        'UNIVERSAL'                   => 0.11,
        'URI'                         => 1.36,
        'URI::Fetch'                  => 0.08,
        'version'                     => 0.76,
        'XML::Elemental'              => 2.1,
        'XML::NamespaceSupport'       => 1.09,
        'XML::SAX'                    => 0.96,
        'XML::Simple'                 => 2.14,
        'YAML::Tiny'                  => 1.12,
=======

# required NoXS
        'Algorithm::Diff'          => '1.1902',
        'Cache'                    => '2.04',
        'CGI'                      => '3.45',
        'Class::Accessor'          => '0.22',
        'Class::Data::Inheritable' => '0.06',
        'Class::Trigger'           => '0.1001',
        'Data::ObjectDriver'       => '0.06',
        'File::Copy::Recursive'    => '0.23',
        'Heap::Fibonacci'          => '0.71',
        'HTML::Diff'               => '0.561',
        'Image::Size'              => '2.93',
        'Jcode'                    => '0.88',
        'JSON'                     => '2.12',
        'Locale::Maketext'         => '1.13',
        'Log::Dispatch'            => '2.26',
        'Log::Log4perl'            => '1.3',
        'Lucene::QueryParser'      => '1.04',
        'LWP'                      => '5.831',
        'Params::Validate'         => '0.73',
        'Sub::Install'             => '0.925',
        'TheSchwartz'              => '1.07',
        'URI'                      => '1.36',
        'version'                  => '0.76',
        'YAML::Tiny'               => '1.12',

#required XS
        'Digest::SHA1' => '0.06',
        'HTML::Parser' => '3.66',
        'DBI'          => '1.21',

#optional
        'bignum'                => '0.17',
        'Crypt::DH'             => '0.06',
        'IO::Scalar'            => '2.110',
        'Mail::Sendmail'        => 0,
        'Math::BigInt'          => '1.63',
        'MIME::Charset'         => '0.044',
        'MIME::EncWords'        => '0.040',
        'Net::OpenID::Consumer' => '1.03',
        'Path::Class'           => '0.21',
        'SOAP::Lite'            => '0.710.08',
        'XML::NamespaceSupport' => '1.09',
        'XML::SAX'              => '0.96',
        'XML::Simple'           => '2.14',
>>>>>>> tima/lh-531-extlib-reset
```

**Comment by jayallen** [comment]
Nevermind. I pushed it as is.  Can you follow up with a commit cleaning up the merge? Thanks

**Pull request merged**
