### PR TITLE
Lh664 missing depends

### PR DESCRIPTION
**Pull request by tima**
This is a redo of this ticket/branch that I hope gets it right.

### CODE REVIEW

**Comment by jayallen** [comment]
Nope, same thing... See https://github.com/openmelody/melody/pull/178

Let's try this a different way.  Is this the only commit you want pushed? https://github.com/tima/melody/commit/872810f5a6470b5901942e79ed46c25f79047ace

**Comment by jayallen** [comment]
I assume it was.  I cherry picked that single commit to master and just pushed. Re-open this if there was another.

**Comment by jayallen** [comment]
...otherwise, you can delete this branch

**Comment by tima** [comment]
No that was it. I guess unscrewing that branch generated a lot of unnecessary commit that I wasn't sure was needed.

**Pull request closed without merging**
