### PR TITLE
Lh366 bundle purge logs

### PR DESCRIPTION
**Pull request by MikeThomsen**
This was resolved by adding PurgeActivityLog 0.3.

### CODE REVIEW

**Comment by jayallen** [comment]
Holding on this one until we have a better consensus.

**Comment by jayallen** [comment]
Same question here. Did you delete your lh366-bundle-purge-logs branch and, if so, was the above the only checkin?

**Comment by MikeThomsen** [comment]
Yes

**Comment by jayallen** [comment]
Done, please delete lh366-bundle-purge-logs

**Pull request closed without merging**
