### PR TITLE
Bug 515 fix site url must be absolute

### PR DESCRIPTION
**Pull request by byrnereese**

### CODE REVIEW

**Comment by jayallen** [comment]
Hey Byrne, can you rebase this against the most recent openmelody/master.

```
git remote update
git co bug-515-fix-site-url-must-be-absolute
git rebase openmelody/master
```

Then, all of those checkins, if they remain separate (which is fine) need Lighthouse declarations so:

```
git rebase -i openmelody/master    # + reword
```

Please see the [Contributor Guidelines section on Commit_Documentation](http://wiki.openmelody.org/Contributor_Guidelines#2._Commit_Documentation) for details of what I'm looking for.

**Comment by byrnereese** [comment]
Done.

**Comment by jayallen** [comment]
Did you repush -f the branch after the rewording because I'm still seeing commits without Lighthouse declarations.

**Comment by byrnereese** [comment]
I think I mis-understood - must every commit bear the `[#515]` text to link the commit to the bug? I was just adding the `[#515 state:resolved]` to the last commit.

**Comment by jayallen** [comment]
Yep.  Think of it this way: Only commits with Lighthouse declarations get attached to the lighthouse ticket.  Also, if any old person goes to say, [this commit](https://github.com/byrnereese/melody/commit/f14f638a4f1a3c5e0fda0caf1688d4884896ec26) on GitHub, they have no way of knowing the full context of that change without seeing the lighthouse ticket #. Further, the person who compiles the release notes (hi! :-) has that same problem.

I know I wrote this somewhere in even more detail than on the page I linked to above but I can't figure out where.  Essentially branches with multiple commits for the same ticket should look like this:
- #NNN state:open
- #NNN
- #NNN
- #NNN (and so on...)
- #NNN state:resolved

Multiple commits done in this way are perfectly fine even if they are small.  However, if it makes sense to squash them together, and detail all of the changes in a single commit note, you're welcome to do that too.  The only caveat is not to let any one commit get TOO big or do too many things at once because having separate commits makes it very easy to revert just a _single_ commit if it's found to be necessary later on.

**Comment by jayallen** [comment]
I went ahead and rebased this branch, rewrote all the commits and pushed.  You can delete it now.

**Pull request closed without merging**
