### PR TITLE
Bug 371 theme manager dep extrav

### PR DESCRIPTION
**Pull request by byrnereese**
Squashed tons of warnings across the app. Touched MT::CMS::Plugin, MT::Component, Theme Manager and Config Assistant.

### CODE REVIEW

**Comment by jayallen** [comment]
Dude.  I don't even know what to make of this one.  Can you get to the page at http://github.com/openmelody/melody/pull/53 to look at this?

**Comment by jayallen** [comment]
Nevermind. Using GitX, I figured out what you did.  Only the last four commits above are unique to this branch.

**Comment by jayallen** [comment]
Shit, I just impressed even myself.  I created a branch called byrnereese-bug-371-theme-manager-dep-extrav from your branch and in one command, put the last four commits squarely on the end of my master branch which I use for integration and pushing:

```
git rebase --onto master byrnereese/master byrnereese-bug-371-theme-manager-dep-extrav
```

See [git-rebase](http://www.kernel.org/pub/software/scm/git/docs/git-rebase.html) for an explanation of that cool command...

**Comment by byrnereese** [comment]
You need to be teaching classes in this. Your fu is strong my friend. Very strong.

**Pull request closed without merging**
