### PR TITLE
Bug 408 tags unit test

### PR DESCRIPTION
**Pull request by byrnereese**
Fixed!

### CODE REVIEW

**Comment by jayallen** [comment]
Same with this one. Go to http://github.com/openmelody/melody/pull/54 to see it.  It looks to me like you did a merge or something with your master branch instead of simply rebasing.  Ping me when you're online and I'll show you what I'm talking about.

I can't merge this as is...

**Comment by byrnereese** [comment]
Why do I keep screwing this up. I swear, I am following the directions of the wiki!

**Comment by jayallen** [comment]
I think you just gave us the answer!  Can you tell me exactly which wiki page you're looking at?  And to be clear, does this mean you're NOT using the shell script I posted for you in one of your past pull requests?  Do you know which shell script I'm talking about?

**Comment by jayallen** [comment]
Shell script here: http://github.com/openmelody/melody/pull/45

**Comment by jayallen** [comment]
Same kind of resolution as your other.  You can get rid of your bug-371-theme-manager-dep-extrav and bug-408-tags-unit-test branches now.

**Pull request closed without merging**
