### PR TITLE
Lh255 bundle pqmanager

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by jayallen** [comment]
Holding on this one until we have a better consensus.

**Comment by jayallen** [comment]
Same question here. Did you delete your lh255-bundle-pqmanager branch and, if so, was the above the only checkin?

**Comment by MikeThomsen** [comment]
Yes

**Comment by jayallen** [comment]
Done, please delete lh255-bundle-pqmanager

**Pull request closed without merging**
