### PR TITLE
Lh664 missing depends

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Comment by jayallen** [comment]
Hey Tim, in the future, if you perltidy, can you do it in its own commit?  That way it isn't wrapped up with an actual non-perltidy change to the software.  Thx

**Comment by jayallen** [comment]
Crap, actually, I'm not going to be able to merge this change because you perltidied files that have been changed since the commit you based your branch off of (which is, again, very old),  Can you separate out your dependency change and repush this branch with a -f?

**Comment by tima** [comment]
I'm still cleaning up from a major relaunch that their blogs was a part of. I'll try and do this as soon as I can. Besides the separate commit, I need to know when I should run something through perltidy.

**Comment by jayallen** [comment]
Ah okay, I'll close this for now. Just issue a new pull request when you're ready.  As for your second question: It's a great one and I'll bring that to the mailing list

**Pull request closed without merging**
