### PR TITLE
Lh784 plugin detection tag

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by jayallen** [comment]
This has been postponed until after the 1.0 launch according to Tim's email response to my question about its status posted to the mailing list.

**Comment by MikeThomsen** [comment]
Ok. It doesn't matter whether it's 1.0 or 1.1, but once users start writing themes it'll be imperative to have that in order to let them match our competition's ability to selectively support plugins.

**Comment by jayallen** [comment]
I don't disagree that this is a good and needed feature. My nite was mainly for my own benefit so later on I know what's going on with it,

**Comment by jayallen** [comment]
I just merged this into a new Melody 1.1 branch

**Comment by jayallen** [comment]
https://github.com/openmelody/melody/commits/melody-1.1

**Pull request closed without merging**
