### PR TITLE
Lh 633 fix template creation

### PR DESCRIPTION
**Pull request by byrnereese**

### CODE REVIEW

**Comment by jayallen** [comment]
Sounds to me like this should be done on the object level, don't you think?  Otherwise, won't applications that are NOT the CMS who use that particular form have the same problem?

What do you think of this fix?  http://code.sixapart.com/trac/movabletype/changeset/5371/trunk/lib/MT/Revisable.pm

**Comment by byrnereese** [comment]
Maybe do it in both places? Template AND object level?

**Comment by jayallen** [comment]
Well, why?

**Comment by jayallen** [comment]
Don't we have the same exact problems with entry creation?  If we're dealing with the lack of a default value in the field for multiple objects, we have an object-level problem, not a CMS problem.

**Comment by jayallen** [comment]
By the way, if you can, can you base this change off of release-1.0b2, not master.

**Pull request merged**
