### PR TITLE
Tima merge conflicts

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Comment by jayallen** [comment]
Err, was this in place of the other one or in addition to?  The second one still has merge conflicts in it and removes all the themes I just put back in.

**Comment by tima** [comment]
Replace. I rebased the last five commits in the mainline covering the span where conflicts occurred squashing them to try and cut down on the noise in the logs.

**Comment by tima** [comment]
So was I suppose to make changes on top of what was there and go back and resolve the conflicting commits?

I'm at a stand still for now because I had a couple of more things to do relating to those two files and I'm not sure what the right course is.

**Comment by jayallen** [comment]
```
git remote update
git checkout -b fixin-merge-conflicts openmelody/master
# [ edit check.cgi and Makefile.PL; perltidy ]
git commit -a -m"Blah blah blah blah"
git push origin fixin-merge-conflicts
# Issue pull request
```

**Pull request merged**
