### PR TITLE
Lh689 smartypants filter

### PR DESCRIPTION
**Pull request by danwolfgang**

### CODE REVIEW

**Comment by jayallen** [comment]
Wait, Dan did the presence of the perl files affect the plugin?

**Comment by danwolfgang** [comment]
Yes, the perl versions of the plugin were being used, not the config.yaml. After removing the .pls, I found that it still wasn't working and made a change to call the SmartyPants method correctly.

**Comment by jayallen** [comment]
So if you put the perl plugins back now does everything still work?  The perl plugins should be completely ignored if the config.yaml initialization succeeds.  If not, please file a bug against the plugin framework assigned to me.

**Comment by danwolfgang** [comment]
I added the perl plugins back in, and everything works properly. So perhaps because the configy.yaml version of the plugin was failing it was falling back to the .pl plugin? Anyway, it's all good now.

**Comment by jayallen** [comment]
That must be the case.  I added unit tests (420ea260636730ff4a495d67ec30101204246d44 and a87ba829ea4ec1c02ff538edefa887357f241d6c) to make sure all was working as desired with the plugin init framework so I'm at least confident about that part.

**Pull request merged**
