### PR TITLE
Merge multiblog fix plugin - fixes #365

### PR DESCRIPTION
**Pull request by byrnereese**

### CODE REVIEW

**Comment by jayallen** [comment]
No unit test, no POD, no documentation?

**Comment by byrnereese** [comment]
There is no POD and no docs, because it is a bug. It is making Melody behave according to already existant documentation.

As for the unit test. No I have not implemented one. I will be honest though: I don't know how.

**Comment by jayallen** [comment]
Well, you wrote a lot in your commit note.  In the future, someone will look at this new module and say, "I wonder what this is for?"  That's what we need in the POD.

As far as the unit test, that's a very good thing to know.  I can help with this but it's imperative that you pick it up because our future is all about unit testing.

**Comment by jayallen** [comment]
BTW, did you see 6A's response? http://bugs.movabletype.org/?100619

**Comment by byrnereese** [comment]
I did. I disagree with their assessment. Relying exclusively upon include and exclude blog URL parameters is hackish and insecure. a) it reveals the ID of a blog that is clearly intended to be excluded, b) removing the URL parameter makes it easy for anyone to hack the URL to reveal results.

That being said, the configuration directives are an ok mechanism. But we are still dealing with a fundamental disconnect here. We are treating two different applications with regards to aggregation and privacy inequally. Personally, I think the determination of "Resolved (By Design)" is lazy. We should endeavor to make Multiblog more intuitive and more complete, and not rely upon hard-to-edit-for-common-user config directives to achieve a simple result. 

With regards to making it hard to debug - I suppose that is only a matter of opinion. If Log4MT was installed we could easily log some debug code to leave some trace behind as to what the code is doing. 

If you tend to agree with Six Apart, I could add an option to the MultiBlog plugin to enable this feature or not.

**Comment by byrnereese** [comment]
You should pull from this branch again. POD docs updated.

**Comment by jayallen** [comment]
Oh, I don't agree or disagree with anyone in this case.  I frankly didn't even read the bug note beyond noting their resolution.  At this point, I can only assume you[1] know what in the hell you're doing.  I only have time for asking questions that confirm you've done your due diligence.  

This is why we need unit tests: Unit tests don't lie and when they do, the can be updated to tell the truth.

[1] - and every committer other than Mike

**Comment by jayallen** [comment]
Commited, push shortly

**Pull request closed without merging**
