### PR TITLE
Lh415 melody util test podcoverage

### PR DESCRIPTION
**Pull request by tima**

### CODE REVIEW

**Comment by jayallen** [comment]
Pushed

**Comment by jayallen** [comment]
FWIW, your commit message said 405 not 415.  I only noticed that after 405 got resolved prematurely.

**Comment by tima** [comment]
Crap. I caught that, did an amend and did a non-fastword push up to my repo. I guess you where too fast for me. Sorry.

**Comment by jayallen** [comment]
No biggie.  I handled it.

**Pull request merged**
