### PR TITLE
Lh364 merge system widget menu

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by jayallen** [comment]
Again, waiting for Dan to weigh in...

**Comment by MikeThomsen** [comment]
Dan left a message here about his opinion: https://openmelody.lighthouseapp.com/projects/26604/tickets/364-merge-system-widget-menu-option-plugin-in-to-core

He seems to be cool with it being added. His preference is that it only be enabled if there are global widgets. I don't agree with that (that was the extent of our exchange so far) as I think leaving it enabled at all times would be both slightly faster (no DB lookup) and reduce the number of clicks to get to the global widgets when a user wants to create one.

**Comment by jayallen** [comment]
Hey, did you delete your lh364-merge-system-widget-menu?  I hadn't yet integrated the changes.  Was the above commit the only commit?

**Comment by MikeThomsen** [comment]
Yes

**Comment by jayallen** [comment]
Cool. Committed.

**Pull request closed without merging**
