### PR TITLE
Lh343 auto dirification

### PR DESCRIPTION
**Pull request by MikeThomsen**
I ran t/62-asset.t and it reported no errors. I've tested it with a few files on my blog and it worked there as well.

### CODE REVIEW

**Comment by jayallen** [comment]
I don't know if you meant to do this or not but you handily deleted your branch for this work and #529.  Assuming you didn't mean to do that, you're luckly that I happened to check out both the other day and still had the branches.So, should I keep them for you or did you mean to lose them?

**Comment by MikeThomsen** [comment]
I pulled it because I rebased it for you. If you want to merge it as is, be my guest.

**Comment by jayallen** [comment]
Rebasing it "for me" would usually indicate that it's accessible "by me". no? 

https://github.com/mikert/melody/branches  :-)

**Comment by jayallen** [comment]
In case that wasn't clear: While you may be rebasing you're local branch or something, I have no way of knowing that because you deleted the branch entirely from GitHub.  If a branch doesn't exist on GitHub, it doesn't exist to me.  Hence "you deleted your branch".

**Comment by MikeThomsen** [comment]
I was going to push it out and close this pull request and reissue it. Other things got in the way. C'est la vie...

**Pull request closed without merging**
