### PR TITLE
Lh760 identifiers attr in widgetset tags

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by tima** [comment]
Before I merge this I need some feedback. I merged in this commit from Byrne before I say this pull request.

https://github.com/byrnereese/melody/commit/3ffb3e35c30905301880881d6d7758c12944a639

How does it relate to this pull request? It's awful similar. Two approaches to the same problem perhaps?

**Comment by MikeThomsen** [comment]
I don't think they relate at all. My commit's purpose was to add an identifier attribute to the WidgetSetLoop tag; Byrne's adds a few local hashref items to $var for use inside the loop.

**Comment by byrnereese** [comment]
What mike said.

**Comment by tima** [comment]
OK. Merged. Please delete the branch now.

**Pull request merged**
