### PR TITLE
Lh756 latest jquery ui

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by jayallen** [comment]
Hey Mike, I'm building RC1 and fixing some issues and inconsistencies related to optimize_ui which have come up during the build. So I thought I'd include this pull request since it's related.  

What I'm wondering is what, if anything, should Melody load by default of jQueryUI? Movable Type loads jquery.ui.all and the minified version when optimize_ui is true. Is there a reason we shouldn't do the same?  And if not, can you get me a minified version of it?  There doesn't seem to be one in the files that you checked in.

**Comment by jayallen** [comment]
Also we don't seem to have a jquery.min.js.  If you're going to create another commit, can you include that as well?

**Comment by jayallen** [comment]
Related: The ticket I filed and am working on: https://openmelody.lighthouseapp.com/projects/26604-melody/tickets/806

**Comment by MikeThomsen** [comment]
I fixed that and rebased. Closing and resending the pull.

**Pull request closed without merging**
