### PR TITLE
[#881 state:resolved] Updated internal jQuery to 1.5.2

### PR DESCRIPTION
**Pull request by MikeThomsen**

### CODE REVIEW

**Comment by tima** [comment]
Mike: What fixes does this release cover that we should include that this must be in 1.0? My concern is that we will introduce some bug or incompatibility for the final release.

**Comment by MikeThomsen** [comment]
It's a 1.1 fix. I didn't intend for it to get handled right away. Just wanted to knock this one out while I remembered it.

**Comment by jayallen** [comment]
Ah CRAP.  I didn't look here before merging the branch.  In the future please, please, please base your future development work off of the branch dedicated to that future version (melody-1.1 in this case).  Reverting the commit now.

**Comment by jayallen** [comment]
Switched to melody-1.1 branch...

**Pull request merged**
