### PR TITLE
Bug 507 change default asset folder

### PR DESCRIPTION
**Pull request by byrnereese**

### CODE REVIEW

**Comment by jayallen** [comment]
> [#507 state:resolved] Changed the default upload path for new assets.

It would have been sweet if you had said what you changed it to in your commit note because that's what both the user and the person compiling the release notes really care about...

**Comment by jayallen** [comment]
Jesus, man. You don't even say what you're changing it to in the [ticket](https://openmelody.lighthouseapp.com/projects/26604-melody/tickets/507).  Please rectify that.

**Comment by jayallen** [comment]
In fact, while you're at it, fix your commit note:

```
# Checkout the branch
git checkout bug-507-change-default-asset-folder

# Interactive rebase - Have you don't this yet? If not, learn this...
git rebase -i bd631e1e       # The commit you created this branch from
  #     when your editor pops up, look for the line with 
  #     "[507 state:resolved]" and change the "pick" to "reword"
  #     Save and close, then edit the commit note in the new window
  #     to say what you're changing it to, save and close again

# Get the latest and put your changes on top
git remote update && git rebase openmelody/master

# Get the name of your personal repo... It was origin, but I think you screwed with origin's URL so...
repo=$(git remote -v | egrep 'byrnereese.*push' | awk '{print $1}')

# Repush the branch forcibly to $repo
git push -f $repo bug-507-change-default-asset-folder
```

Then come back here and tell me it's done at which point I'll integrate your branch

**Comment by byrnereese** [comment]
I am back. And I am done.

**Pull request merged**
